### PR TITLE
Add simple Raku solution.

### PR DESCRIPTION
**Pull request by rawleyfowler**

### CODE REVIEW

**Comment by eatnumber1** [comment]
Looks good to me, can you add Raku to the languages table in the top-level readme?

**Comment by rawleyfowler** [comment]
@eatnumber1 should be good to go!

**Comment by worr** [comment]
@eatnumber1 there might be more work here, altho tbh I'm fine with doing it after this gets merged.

Raku is the new name of perl6. We already have perl6 solutions, so we should merge the two dirs under this new raku dir. I don't think we need to make @rawleyfowler do it; we can do it after merging, but I'll leave the decision up to you.

**Comment by rawleyfowler** [comment]
@worr, good catch. I can do this if @eatnumber1 thinks it's necessary.

**Comment by eatnumber1** [comment]
Aha, good catch @worr. Yeah please move the perl6 stuff into a raku directory if you're willing (and fix the readme too).

**Comment by rawleyfowler** [comment]
@eatnumber1 Should be good to go 😃

**Review by worr — APPROVED** [review]
I'm good with this. Sorry for the extra work

**Comment by rawleyfowler** [comment]
@worr No problem!

**Pull request merged**
