### PR TITLE
Added new python solution.

### PR DESCRIPTION
**Pull request by ssundarraj**

### CODE REVIEW

**Comment by eatnumber1** [comment]
Why is this approach novel? It looks like you're doing almost the same thing as [xchrdw](https://github.com/eatnumber1/goal/blob/master/solved/python/xchrdw/goal.py), but with more code.

**Comment by ssundarraj** [comment]
That's using count variable, this is using a list. Not a major difference, but there is a difference.

**Comment by eatnumber1** [comment]
Agreed that there is a difference, but the differences aren't really relevant to the problem itself. Your approach is summarized as "use lambdas with internal state", for which there are many Python solutions.

A novel solution would be something like finding a way to do this using [continuations](https://en.wikipedia.org/wiki/Continuation-passing_style), or clever tricks with how the Python VM works.

I don't think this is novel enough, and I'd like to avoid cluttering the solutions (more than they are already) with variations on the same approach.

**Comment by ssundarraj** [comment]
Fair enough :+1:

**Pull request closed without merging**
